/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ticketBooking;

import org.ticketBooking.entities.Train;
import org.ticketBooking.entities.User;
import org.ticketBooking.services.UserBookingService;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.UUID;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        System.out.println("Running Train booking System");
        Scanner scanner = new Scanner(System.in);

        int option =0;

        UserBookingService userBookingService;

        try{
            userBookingService = new UserBookingService();
        }catch(IOException ex){
            System.out.println("There is something wrong");
            return;
        }

        while(option!=7){
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Booking");
            System.out.println("4. Search Train");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");

            option =scanner.nextInt();

            Train trainSelectedForBooking =new Train();

            switch(option){
                case 1:
                    System.out.println("Enter Username to signup");
                    String nameToSignUp=scanner.next();

                    System.out.println("Enter the password to signup");
                    String passwordToSignUp=scanner.next();

                    User userToSignup =new User(nameToSignUp, passwordToSignUp , UserServiceUtil.hashPassword(passwordToSignUp), new ArrayList<>(), UUID.randomUUID().toString());
                    userBookingService.signUp(userToSignup);
                    break;

                case 2:
                    break;
            }
        }


    }
}
